### ISSUE TITLE
Schedule assignment serializer read-only fields

### ISSUE THREAD

**Issue by pipieter** [SELab-2/Dr-Trottoir-3#47]
The PATCH request for a Schedule Assignment only allows users to be changed. The assigned_date and schedule_definition field must remain the same. For the moment this is done by creating a custom update method in the ViewSet class, but it should be also be doable with [read-only fields](https://www.django-rest-framework.org/api-guide/serializers/#specifying-read-only-fields).

See also #37

**Comment by ChewingBever** [comment]
Too difficult to change.
